### ISSUE TITLE
Getting error `cp: omitting directory 'colx-1.0.3'`

### ISSUE THREAD

**Issue by jsatka** [ColossusCoinXT/COLX_MN_Installer#1]
Getting error `cp: omitting directory 'colx-1.0.3'` on Ubuntu 16.04. Culprit is the line:
https://github.com/ColossusCoinXT/COLX_MN_Installer/blob/master/COLX_MN_Installer.sh#L29

**Comment by jsatka** [comment]
Looks like the row 29

```
  cp colx* /usr/local/bin
```

should be 

```
  cp colx*/bin/* /usr/local/bin
```

to copy the colx binaries from colx-1.0.3/bin to /usr/local/bin

If the contents in lib and include folders should be copied, too, to /usr/local/lib and /usr/local/include, then replacing with something like

```
  for DIRPATH in `echo colx*/*`; do
    DIRNAME=$(echo $DIRPATH | awk -F'/' '{print $NF}')
    cp $DIRPATH/* /usr/local/$DIRNAME
  done
```

**Comment by ciwox** [comment]
This has been fixed in the newest version.
